var wordDatabase = {
    easy: {
        "and": "I have a cat and a dog.",
        "arm": "I can raise my arm up high.",
        "ask": "If you don't know, you should ask the teacher.",
        "bag": "I carry my books in my school bag.",
        "ball": "Let's play with the red ball.",
        "bat": "A baseball player uses a bat to hit the ball.",
        "bath": "I take a warm bath before bed.",
        "bed": "I sleep in my cozy bed every night.",
        "bee": "A bee makes sweet honey.",
        "big": "An elephant is a big animal.",
        "bike": "I like to ride my bike in the park.",
        "bird": "A little bird is singing on the branch.",
        "black": "A penguin is black and white.",
        "blue": "The sky is blue on a sunny day.",
        "boat": "The boat sails on the water.",
        "book": "I love to read a good book.",
        "box": "I keep my toys in a big box.",
        "boy": "The boy is playing with his toy car.",
        "bread": "We eat toast, which is made from bread.",
        "brown": "A teddy bear is often brown.",
        "bus": "We ride the yellow bus to school.",
        "but": "I want to play, but I have to do my homework first.",
        "bye": "We say bye when we leave.",
        "cake": "We celebrate with a delicious birthday cake.",
        "car": "The car is parked in the garage.",
        "cat": "The little cat says 'meow'.",
        "catch": "Let's play catch with the ball.",
        "chair": "Please sit on the chair.",
        "clap": "We clap our hands after a good performance.",
        "clean": "Please clean your room.",
        "close": "Please close the door quietly.",
        "come": "Please come here for a moment.",
        "cow": "A cow gives us milk.",
        "cross": "We need to cross the street safely.",
        "dad": "My dad is tall and strong.",
        "day": "A day has a morning, afternoon, and night.",
        "desk": "I do my homework at my desk.",
        "dog": "The dog wags its tail when it's happy.",
        "door": "Please open the front door.",
        "draw": "I like to draw pictures of animals.",
        "duck": "A duck can swim in the pond.",
        "ear": "I listen to music with my ear.",
        "eat": "We eat our lunch at noon.",
        "egg": "I had a boiled egg for breakfast.",
        "end": "This is the end of the story.",
        "eye": "I can see the beautiful flowers with my eye.",
        "face": "She has a happy smile on her face.",
        "find": "I can't find my missing sock.",
        "fish": "A fish swims in the water.",
        "five": "I have five fingers on each hand.",
        "fly": "A bird can fly high in the sky.",
        "food": "Apples, bread, and milk are all types of food.",
        "foot": "I wear a shoe on my foot.",
        "for": "This gift is for you.",
        "frog": "A frog can jump very high.",
        "from": "I am from a small town.",
        "fun": "Playing games is a lot of fun.",
        "get": "I will get a book from the shelf.",
        "girl": "The girl is riding her scooter.",
        "give": "Please give me the red crayon.",
        "go": "It's time to go to school.",
        "good": "You did a good job on your drawing.",
        "hand": "I wave my hand to say hello.",
        "hat": "I wear a hat to keep my head warm.",
        "have": "I have a blue toy car.",
        "head": "I wear a helmet to protect my head.",
        "hear": "I can hear the birds singing.",
        "help": "Can you help me, please?",
        "here": "Please come and sit here.",
        "hi": "When I see my friend, I say hi.",
        "him": "I gave the book to him.",
        "his": "That is his pencil.",
        "hit": "You use a bat to hit the ball.",
        "hold": "Please hold my hand when we cross the street.",
        "home": "My home is where my family lives.",
        "hot": "The sun makes the day hot.",
        "house": "We live in a small blue house.",
        "how": "How are you feeling today?",
        "jump": "I can jump up and down.",
        "kick": "You can kick a soccer ball with your foot.",
        "kid": "A young child is often called a kid.",
        "know": "I know the answer to the question.",
        "leg": "I have two legs to walk and run.",
        "like": "I like to eat strawberries.",
        "line": "Please stand in a straight line.",
        "look": "Look at the beautiful rainbow!",
        "love": "I love my family very much.",
        "man": "The man is reading a newspaper.",
        "mat": "We wipe our feet on the mat before coming inside.",
        "milk": "I drink milk with my breakfast.",
        "mom": "My mom gives me a hug.",
        "name": "My name is Tom.",
        "near": "The park is near our house.",
        "nest": "A bird builds its nest in a tree.",
        "new": "I got a new toy for my birthday.",
        "next": "Who's next in line?",
        "nice": "It's nice to meet you.",
        "nose": "I can smell flowers with my nose.",
        "not": "This is not my book.",
        "now": "It is time to go to bed now.",
        "old": "My grandpa is very old.",
        "one": "I have one nose.",
        "out": "Let's go out to play.",
        "park": "We play on the swings at the park.",
        "pen": "I write in my notebook with a blue pen.",
        "pig": "The pig plays in the mud.",
        "play": "The children love to play outside.",
        "put": "Please put your toys away.",
        "rain": "The rain makes the grass wet.",
        "read": "I like to read a story before I go to sleep.",
        "red": "An apple is often red.",
        "ride": "I want to ride my bicycle.",
        "room": "This room is where we watch TV.",
        "run": "I can run very fast.",
        "sad": "The boy was sad when he lost his toy.",
        "say": "Can you say 'thank you'?",
        "see": "I can see birds flying in the sky.",
        "she": "She is my sister.",
        "sit": "Please sit down on the chair.",
        "six": "I am six years old.",
        "sky": "The sky is blue on a sunny day.",
        "stop": "Stop at the red light.",
        "sun": "The sun shines bright and warm.",
        "swim": "Fish swim in water.",
        "tail": "A dog wags its tail when it's happy.",
        "take": "Please take your book to school.",
        "talk": "I like to talk with my friends.",
        "tall": "A giraffe is very tall.",
        "ten": "I can count to ten.",
        "that": "That book belongs to my sister.",
        "the": "The cat is sleeping.",
        "then": "First we study, then we play.",
        "this": "This is my favorite toy.",
        "time": "It's time to go to bed.",
        "toy": "My favorite toy is a teddy bear.",
        "tree": "Apples grow on the tree.",
        "try": "I will try my best to help.",
        "two": "I have two eyes.",
        "up": "The balloon floats up in the air.",
        "use": "We use pencils to write.",
        "wait": "Wait for me, please!",
        "walk": "Let's walk to the park together.",
        "wall": "The picture hangs on the wall.",
        "want": "I want to play outside.",
        "warm": "The sun makes us feel warm.",
        "wash": "Wash your hands before eating.",
        "way": "This is the way to the library.",
        "we": "We are friends.",
        "wet": "My shoes got wet in the rain.",
        "what": "What time is it?",
        "when": "When does school start?",
        "who": "Who wants to play with me?",
        "why": "Why is the sky blue?",
        "win": "Our team will try to win the game.",
        "with": "I play with my friends.",
        "word": "Can you spell this word?",
        "work": "My parents work every day.",
        "yes": "Yes, I would like some juice.",
        "you": "You are my best friend.",
        "zoo": "We see animals at the zoo.",
        "bear": "The bear likes to eat honey.",
        "bell": "The school bell rings at lunch time.",
        "bug": "A small bug crawls on the leaf.",
        "cap": "I wear my cap when it's sunny.",
        "cup": "I drink water from my cup.",
        "den": "The fox sleeps in its den.",
        "dot": "Draw a dot on the paper.",
        "fan": "The fan keeps us cool.",
        "fog": "The fog makes it hard to see.",
        "hug": "Mom gives me a warm hug.",
        "jam": "I like strawberry jam on toast.",
        "lap": "The cat sits on my lap.",
        "map": "The map shows us where to go.",
        "nap": "I take a short nap after lunch.",
        "net": "We catch fish with a net.",
        "paw": "The dog hurt its paw.",
        "pin": "Pin the picture on the board.",
        "pot": "The plant grows in a pot.",
        "rug": "We sit on the rug to read stories.",
        "sip": "I sip my hot chocolate carefully.",
        "tap": "Tap the drum to make music.",
        "web": "The spider makes a web.",
        "wig": "The clown wears a funny wig.",
        "zip": "Please zip up your jacket."
    },
    medium: {
        "about": "This book is about a brave little mouse.",
        "after": "We play after lunch.",
        "again": "Can we sing that song again?",
        "angry": "The baby gets angry when he is hungry.",
        "animal": "A lion is a wild animal.",
        "answer": "Please raise your hand to answer the question.",
        "apple": "An apple a day keeps the doctor away.",
        "baby": "The baby is sleeping in the crib.",
        "basket": "Put the apples in the basket.",
        "behind": "The cat is hiding behind the sofa.",
        "between": "The ball is between the two boxes.",
        "brother": "My brother is older than me.",
        "button": "Press the button to start the game.",
        "candy": "Eating too much candy is not good for your teeth.",
        "carrot": "A rabbit loves to eat a crunchy carrot.",
        "chicken": "A chicken lays eggs.",
        "children": "All the children are laughing in the playground.",
        "circle": "The moon is shaped like a circle.",
        "cookie": "Grandma bakes the best cookies.",
        "corner": "The cat is sleeping in the corner.",
        "cousin": "My aunt's son is my cousin.",
        "dinner": "We eat dinner in the evening.",
        "doctor": "The doctor helps sick people feel better.",
        "dragon": "The dragon in the story breathed fire.",
        "driver": "The bus driver takes us to school.",
        "during": "We stay inside during the rain.",
        "early": "I wake up early for school.",
        "enjoy": "I enjoy playing with my friends.",
        "family": "My family loves to spend time together.",
        "father": "My father reads me a bedtime story.",
        "finger": "I have five fingers on each hand.",
        "flower": "A rose is a beautiful flower.",
        "garden": "We grow flowers and vegetables in our garden.",
        "happy": "I feel happy when I play with my puppy.",
        "helper": "The teacher's helper passes out papers.",
        "hobby": "My hobby is collecting stamps.",
        "inside": "Let's go inside when it rains.",
        "jacket": "I wear a jacket when it is cold.",
        "kitten": "The kitten plays with a ball of yarn.",
        "kitchen": "My mom cooks dinner in the kitchen.",
        "letter": "The letter 'A' is the first letter of the alphabet.",
        "little": "A mouse is a little animal.",
        "monkey": "The monkey swings in the trees.",
        "morning": "We eat breakfast in the morning.",
        "mother": "My mother helps me with my homework.",
        "mouse": "The mouse likes to eat cheese.",
        "music": "I like to dance to music.",
        "never": "Never run into the street.",
        "orange": "An orange is a round, orange-colored fruit.",
        "pencil": "I use a pencil to do my homework.",
        "people": "There are many people at the park.",
        "person": "One person is waiting for the bus.",
        "picture": "I drew a picture of a house.",
        "purple": "Grapes can be purple or green.",
        "rabbit": "The rabbit hops through the garden.",
        "river": "Fish swim in the river.",
        "sister": "My sister helps me with my homework.",
        "spider": "The spider spins a web.",
        "summer": "We go swimming in summer.",
        "table": "We eat dinner at the table.",
        "teacher": "The teacher helps us learn.",
        "tiger": "The tiger has black stripes.",
        "turtle": "A turtle moves slowly on land.",
        "under": "The cat sleeps under the bed.",
        "water": "Plants need water to grow.",
        "window": "Open the window to let fresh air in.",
        "winter": "It snows in winter.",
        "yellow": "The sun is yellow.",
        "berry": "The berry is sweet and red.",
        "bunny": "The bunny hops in the garden.",
        "candy": "The candy is sweet and chewy.",
        "cloudy": "It's cloudy today, no sun.",
        "fairy": "The fairy has sparkly wings.",
        "fluffy": "The kitten has fluffy fur.",
        "foggy": "It's hard to see on foggy days.",
        "funny": "The joke was very funny.",
        "honey": "Bees make sweet honey.",
        "jelly": "I like grape jelly on bread.",
        "kitty": "The kitty purrs softly.",
        "lucky": "I feel lucky today.",
        "muddy": "My shoes got muddy in the rain.",
        "puppy": "The puppy wags its tail.",
        "rainy": "Bring an umbrella on rainy days.",
        "silly": "We tell silly jokes and laugh.",
        "sunny": "It's a sunny day to play outside.",
        "windy": "The windy day blew my hat away.",
        "artist": "The artist paints beautiful pictures.",
        "blanket": "I sleep under a warm blanket.",
        "bracelet": "She wears a pretty bracelet.",
        "bucket": "Fill the bucket with sand.",
        "cactus": "A cactus grows in the desert.",
        "carpet": "The carpet is soft to walk on.",
        "castle": "The princess lives in a castle.",
        "cricket": "We hear the cricket chirp at night.",
        "crystal": "The crystal sparkles in the light.",
        "dolphin": "The dolphin jumps in the ocean.",
        "forest": "Trees grow tall in the forest.",
        "gentle": "Be gentle with small animals.",
        "giant": "The giant tree reaches the sky.",
        "magic": "The magician does magic tricks.",
        "market": "We buy food at the market.",
        "mermaid": "The mermaid swims in the sea.",
        "monster": "The friendly monster makes us laugh.",
        "music": "We dance to happy music.",
        "parrot": "The parrot can copy our words.",
        "pencil": "I draw with my colored pencil.",
        "planet": "Earth is our home planet.",
        "pocket": "I keep coins in my pocket.",
        "puppet": "The puppet show was fun to watch.",
        "rainbow": "The rainbow has seven colors.",
        "rocket": "The rocket flies to space.",
        "secret": "Can you keep a secret?",
        "shadow": "My shadow follows me around.",
        "silver": "The moon shines silver at night.",
        "sparkle": "Stars sparkle in the night sky.",
        "thunder": "Thunder makes a loud boom.",
        "ticket": "We need a ticket for the show.",
        "treasure": "Pirates look for hidden treasure.",
        "turtle": "The turtle walks slowly.",
        "wizard": "The wizard waves his magic wand."
    },
    hard: {
        "afternoon": "We play in the park in the afternoon.",
        "alphabet": "We learn the alphabet from A to Z in school.",
        "apartment": "We live in an apartment on the third floor.",
        "beautiful": "The butterfly has beautiful wings.",
        "butterfly": "The butterfly has colorful wings.",
        "chocolate": "My favorite flavor of ice cream is chocolate.",
        "classroom": "The teacher writes on the board in the classroom.",
        "crocodile": "A crocodile has a long snout and many teeth.",
        "different": "Each snowflake is different.",
        "difficult": "This puzzle is difficult to solve.",
        "dinosaur": "A dinosaur lived long ago.",
        "elephant": "An elephant has a long trunk.",
        "exercise": "Exercise helps keep us healthy.",
        "favorite": "My favorite animal is the lion.",
        "grandfather": "My grandfather tells the best stories.",
        "grandmother": "My grandmother gives the best hugs.",
        "helicopter": "A helicopter has spinning blades on top.",
        "important": "It is important to brush your teeth.",
        "jellyfish": "A jellyfish floats in the sea.",
        "keyboard": "I type letters on the computer keyboard.",
        "language": "English is a language spoken in many countries.",
        "newspaper": "Dad reads the newspaper in the morning.",
        "pineapple": "A pineapple is a sweet fruit that grows in warm places.",
        "playground": "The playground has a slide and a sandbox.",
        "question": "Raise your hand if you have a question.",
        "temperature": "The temperature is high in summer.",
        "together": "Let's play together in the park.",
        "umbrella": "Use an umbrella when it rains.",
        "understand": "I understand the homework now.",
        "uniform": "I wear my school uniform every day.",
        "vegetable": "Carrots are my favorite vegetable.",
        "yesterday": "I went to the park yesterday.",
        "adventure": "We had an adventure in the park.",
        "butterfly": "A butterfly landed on the flower.",
        "caterpillar": "The caterpillar becomes a butterfly.",
        "dragonfly": "The dragonfly has shiny wings.",
        "grasshopper": "The grasshopper jumps very high.",
        "hummingbird": "The hummingbird drinks flower nectar.",
        "kangaroo": "A kangaroo hops with its baby.",
        "ladybug": "The ladybug has red wings with spots.",
        "octopus": "An octopus has eight arms.",
        "penguin": "The penguin swims in cold water.",
        "unicorn": "The unicorn has a magical horn.",
        "waterfall": "The waterfall makes a loud sound.",
        "astronaut": "The astronaut flies in space.",
        "beautiful": "The rainbow is beautiful.",
        "butterfly": "The butterfly has colorful wings.",
        "carnival": "We play games at the carnival.",
        "celebrate": "We celebrate birthdays with cake.",
        "centipede": "A centipede has many legs.",
        "chocolate": "Hot chocolate warms us in winter.",
        "comfortable": "This chair is very comfortable.",
        "community": "We help our community.",
        "dangerous": "It's dangerous to play with fire.",
        "decorator": "The decorator makes rooms pretty.",
        "delicious": "Grandma's cookies are delicious.",
        "detective": "The detective solves mysteries.",
        "dinosaur": "The dinosaur lived long ago.",
        "discovery": "Making a discovery is exciting.",
        "emergency": "Call for help in an emergency.",
        "excellent": "You did an excellent job!",
        "fantastic": "We had a fantastic day.",
        "favorite": "Pizza is my favorite food.",
        "fortunate": "We are fortunate to have friends.",
        "furniture": "The furniture in my room is blue.",
        "generous": "It's good to be generous and share.",
        "happiness": "Playing brings happiness.",
        "hospital": "Doctors work at the hospital.",
        "imagination": "Use your imagination to create stories.",
        "important": "It's important to be kind.",
        "incredible": "You did an incredible job!",
        "instrument": "A piano is a musical instrument.",
        "interesting": "Books can be very interesting.",
        "laboratory": "Scientists work in a laboratory.",
        "librarian": "The librarian helps find books.",
        "marvelous": "That's a marvelous drawing!",
        "medicine": "Medicine helps when we're sick.",
        "mysterious": "The cave looks mysterious.",
        "orchestra": "Many instruments play in an orchestra.",
        "passenger": "Each passenger has a seat.",
        "playground": "We have fun at the playground.",
        "pollution": "We should help stop pollution.",
        "powerful": "The wind is very powerful.",
        "scientist": "A scientist does experiments.",
        "spectacular": "The fireworks were spectacular.",
        "submarine": "A submarine goes under water.",
        "telescope": "Look at stars through the telescope.",
        "temperature": "What's the temperature today?",
        "wonderful": "We had a wonderful time."
    }
}; 